spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/taxi
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: create
    show-sql: true

coordinate:
  start-longitude: 50.189683
  start-latitude: 53.222579
  finish-longitude: 50.102834
  finish-latitude: 53.199131

yandex:
  url: https://taxi-routeinfo.taxi.yandex.net/taxi_info
  clid: ${YANDEX_CLID}
  apiKey: ${YANDEX_APIKEY}
